default_agent: server
agents:
  server:
    name: server
    entrypoint: server.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::318766877259:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-b3eacd3343
      execution_role_auto_create: false
      account: '318766877259'
      region: us-east-1
      ecr_repository: 318766877259.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-server
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: server-btCLLY358w
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:318766877259:runtime/server-btCLLY358w
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-server-builder
      execution_role: arn:aws:iam::318766877259:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-b3eacd3343
      source_bucket: bedrock-agentcore-codebuild-sources-318766877259-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: server_mem-GATcwy50Vh
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:318766877259:memory/server_mem-GATcwy50Vh
      memory_name: server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
