default_agent: sonic2telephonyagent
agents:
  sonic2telephonyagent:
    name: sonic2telephonyagent
    entrypoint: /Users/akalanka/Documents/dev/agentcore/projects/sonic2-telephony/agent/server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/akalanka/Documents/dev/agentcore/projects/sonic2-telephony/agent
    aws:
      execution_role: arn:aws:iam::318766877259:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-33d4ec92aa
      execution_role_auto_create: false
      account: '318766877259'
      region: us-east-1
      ecr_repository: 318766877259.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-sonic2telephonyagent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: sonic2telephonyagent-o4NiyBEeVf
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:318766877259:runtime/sonic2telephonyagent-o4NiyBEeVf
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-sonic2telephonyagent-builder
      execution_role: arn:aws:iam::318766877259:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-33d4ec92aa
      source_bucket: bedrock-agentcore-codebuild-sources-318766877259-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
